apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fim3qd12k-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/fim3qd12k-java-quarkus-gitops